# Generated by Django 4.2.23 on 2026-07-28 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('numero_fiscal', models.CharField(max_length=50, unique=True, verbose_name='Identifiant fiscalité')),
                ('numero_foncier', models.CharField(max_length=50, unique=True, verbose_name='Identifiant foncier (NICAD)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citoyen', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
