# Generated by Django 5.2.3 on 2026-09-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citoyens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='operateur_paiement',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('wave', 'Wave')], help_text='Utilisé pour pré-remplir vos paiements de taxation.', max_length=20, verbose_name='Opérateur de paiement enregistré'),
        ),
    ]
