# Generated by Django 4.2.23 on 2026-08-06 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceJeune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('FINANCEMENT', 'Financement'), ('FORMATION', 'Formation / Accompagnement'), ('FONCIER', 'Foncier / Local'), ('RESEAU', 'RÃ©seau / Partenaires'), ('ADMINISTRATIF', 'DÃ©marches administratives')], max_length=20)),
                ('description', models.TextField()),
                ('lien', models.URLField(blank=True, help_text='Lien externe (site officiel, formulaire...)')),
                ('contact', models.CharField(blank=True, help_text='TÃ©lÃ©phone/email de contact, si utile', max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ressource jeunesse',
                'verbose_name_plural': 'Ressources jeunesse',
                'ordering': ['categorie', 'ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ProjetJeune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_porteur', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ã‚ge')),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quartier', models.CharField(blank=True, max_length=150, verbose_name='Quartier Ã\xa0 Keur Massar Nord')),
                ('titre_projet', models.CharField(max_length=200)),
                ('secteur', models.CharField(choices=[('AGRICULTURE', 'Agriculture / Ã‰levage'), ('COMMERCE', 'Commerce'), ('ARTISANAT', 'Artisanat'), ('NUMERIQUE', 'NumÃ©rique / Tech'), ('EDUCATION', 'Ã‰ducation / Formation'), ('SANTE', 'SantÃ©'), ('ENVIRONNEMENT', 'Environnement / Assainissement'), ('CULTURE', 'Culture / Sport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField()),
                ('besoin_principal', models.CharField(choices=[('FINANCEMENT', 'Financement'), ('LOCAL', 'Local / Terrain'), ('FORMATION', 'Formation / Accompagnement'), ('RESEAU', 'Mise en rÃ©seau / Partenaires'), ('MATERIEL', 'MatÃ©riel / Ã‰quipement'), ('AUTRE', 'Autre besoin')], default='AUTRE', max_length=20)),
                ('details_besoin', models.TextField(blank=True, verbose_name='PrÃ©cisions sur le besoin')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'Ã©tude"), ('valide', 'ValidÃ© par la mairie'), ('rejete', 'Non retenu')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('contacte', models.BooleanField(default=False, verbose_name='ContactÃ© par la mairie')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_jeunes_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet jeune',
                'verbose_name_plural': 'Projets jeunes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='MessageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('envoye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jeunesse.projetjeune')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
    ]
