# Generated by Django 4.2.23 on 2026-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeunesse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetjeune',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='besoin_principal',
            field=models.CharField(choices=[('FINANCEMENT', 'Un financement pour démarrer ou grandir'), ('LOCAL', 'Un local ou un terrain'), ('FORMATION', 'Une formation ou un accompagnement'), ('RESEAU', 'Être mis en relation avec des partenaires'), ('MATERIEL', 'Du matériel ou des équipements'), ('AUTRE', 'Un autre besoin')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='contacte',
            field=models.BooleanField(default=False, verbose_name='Contacté par la mairie'),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='details_besoin',
            field=models.TextField(blank=True, verbose_name='Précisions sur le besoin'),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, verbose_name='Quartier à Keur Massar Nord'),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='secteur',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture, élevage ou pêche'), ('COMMERCE', 'Commerce'), ('ARTISANAT', 'Artisanat'), ('NUMERIQUE', 'Numérique et nouvelles technologies'), ('EDUCATION', 'Éducation et formation'), ('SANTE', 'Santé et bien-être'), ('ENVIRONNEMENT', 'Environnement et assainissement'), ('CULTURE', 'Culture, art et sport'), ('AUTRE', 'Autre secteur')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='projetjeune',
            name='statut',
            field=models.CharField(choices=[('en_attente', "En attente d'étude"), ('valide', 'Validé par la mairie'), ('rejete', 'Non retenu')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ressourcejeune',
            name='categorie',
            field=models.CharField(choices=[('FINANCEMENT', 'Financement'), ('FORMATION', 'Formation / Accompagnement'), ('FONCIER', 'Foncier / Local'), ('RESEAU', 'Réseau / Partenaires'), ('ADMINISTRATIF', 'Démarches administratives')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ressourcejeune',
            name='contact',
            field=models.CharField(blank=True, help_text='Téléphone/email de contact, si utile', max_length=200),
        ),
    ]
