# Generated by Django 4.2.23 on 2026-08-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeunesse', '0002_alter_projetjeune_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetjeune',
            name='cv',
            field=models.FileField(blank=True, help_text='Facultatif — format PDF, 5 Mo maximum.', null=True, upload_to='jeunesse/cv/%Y/%m/', verbose_name='CV (PDF)'),
        ),
    ]
