"""
Django settings for kmsn project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from django.urls import reverse_lazy
# === DASHBOARD ADMIN CUSTOM ===
LOGIN_URL = '/gestion/login/'
LOGIN_REDIRECT_URL = '/gestion/'
LOGOUT_REDIRECT_URL = '/gestion/login/'
# --- FORÇAGE GDAL / GÉO POUR WINDOWS (TOUT EN HAUT) ---
if os.name == 'nt':
    # Cherche automatiquement une installation géo disponible.
    # OSGeo4W est vérifié en premier (c'est celle installée ici),
    # QGIS reste en repli si jamais vous en installez un plus tard.
    GEO_DIRS = [
        r"C:\OSGeo4W",
        r"C:\Program Files\QGIS 3.44.4",
        r"C:\Program Files\QGIS 3.34.2",
        r"C:\Program Files\QGIS 3.34.0",
        r"C:\Program Files\QGIS 3",
    ]
    GEO_DIR = next((path for path in GEO_DIRS if os.path.exists(path)), None)

    if GEO_DIR:
        GEO_BIN = os.path.join(GEO_DIR, 'bin')
        GDAL_DATA = os.path.join(GEO_DIR, 'share', 'gdal')
        PROJ_LIB = os.path.join(GEO_DIR, 'share', 'proj')

        if os.path.isdir(GEO_BIN):
            os.environ['PATH'] = GEO_BIN + os.path.pathsep + os.environ.get('PATH', '')
            if os.path.isdir(GDAL_DATA):
                os.environ['GDAL_DATA'] = GDAL_DATA
            if os.path.isdir(PROJ_LIB):
                os.environ['PROJ_LIB'] = PROJ_LIB

            if sys.version_info >= (3, 8):
                try:
                    os.add_dll_directory(GEO_BIN)
                except Exception:
                    pass

            try:
                dll_files = os.listdir(GEO_BIN)
                gdal_dll = sorted([f for f in dll_files if f.lower().startswith('gdal') and f.lower().endswith('.dll')])
                if gdal_dll:
                    # Prend la dernière en ordre alphabétique (souvent la version la plus complète,
                    # ex: gdal310.dll plutôt que gdalplugins.dll)
                    GDAL_LIBRARY_PATH = os.path.join(GEO_BIN, gdal_dll[-1])
                    if os.path.exists(GDAL_LIBRARY_PATH):
                        os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH

                geos_dll = [f for f in dll_files if f.lower().startswith('geos_c') and f.lower().endswith('.dll')]
                if geos_dll:
                    GEOS_LIBRARY_PATH = os.path.join(GEO_BIN, geos_dll[0])
                    if os.path.exists(GEOS_LIBRARY_PATH):
                        os.environ['GEOS_LIBRARY_PATH'] = GEOS_LIBRARY_PATH
            except Exception:
                pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Chargement du fichier .env (variables d'environnement locales) ---
# En production, ces variables sont normalement fournies directement par
# l'hébergeur (pas de fichier .env sur le serveur) ; load_dotenv() ne fait
# alors simplement rien si le fichier est absent, sans erreur.
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')


def env_bool(nom, defaut=False):
    """Lit une variable d'environnement booléenne ('True'/'False', '1'/'0')."""
    valeur = os.environ.get(nom)
    if valeur is None:
        return defaut
    return valeur.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(nom, defaut=""):
    """Lit une variable d'environnement en liste séparée par des virgules."""
    valeur = os.environ.get(nom, defaut)
    return [item.strip() for item in valeur.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La valeur ci-dessous n'est utilisée QUE si aucune variable d'environnement
# DJANGO_SECRET_KEY n'est définie (dépannage en développement local). En
# production, DJANGO_SECRET_KEY doit impérativement être fournie via .env
# ou les variables d'environnement de l'hébergeur.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-p3!k=0lj1157nc^6=t*&px-$bq)8(f@q*)wj@p!fo*)x#bxb+_',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')

# Domaines autorisés à soumettre des formulaires POST (nécessaire dès que
# le site est servi en HTTPS derrière un vrai nom de domaine).
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', '')


# Application definition

INSTALLED_APPS = [
    # Thème moderne Unfold
    "unfold",
    "unfold.contrib.filters",      # Si vous voulez des filtres avancés
    "unfold.contrib.forms",        # Si vous voulez des formulaires modernes
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # Requis pour PostGIS
    'foncier',
    'comptes',
    'citoyens',
    'jeunesse',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'foncier.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kmsn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "foncier.context_processors.dashboard_counts",
            ],
        },
    },
]

WSGI_APPLICATION = 'kmsn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',  # Moteur PostGIS
        'NAME': os.environ.get('DB_NAME', 'keur_massar_nord_arret_003_008_014'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # Réutilise la même connexion pendant 60s au lieu d'en rouvrir une à
        # chaque requête : gain sensible sur les pages qui font plusieurs
        # appels API rapprochés (géoportail : parcelles + zones + filtres).
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (fichiers uploadés par les utilisateurs : CV, photos de signalement, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Fichiers PRIVÉS (ex : pièces jointes des démarches — cartes d'identité,
# plans...). Volontairement HORS de MEDIA_ROOT : ce dossier n'est jamais
# câblé sur une URL publique (voir kmsn/urls.py). Le seul moyen d'y accéder
# est la vue authentifiée citoyens.views.demande_piece_jointe_view, qui
# vérifie que la personne connectée est bien l'auteur de la demande ou un
# agent — jamais un accès direct par URL devinée.
PRIVATE_MEDIA_ROOT = BASE_DIR / 'media_prive'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Fait correspondre le tag Django 'error' à la classe Bootstrap 'alert-danger'
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# === EMAIL (formulaire de contact) ===
# En développement (DJANGO_EMAIL_BACKEND non défini) : les emails s'affichent
# dans la console au lieu d'être réellement envoyés. En production, définir
# DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend et les
# variables EMAIL_HOST_* correspondantes dans .env.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'contact@keurmassarnord.sn')
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'contact@keurmassarnord.sn')  # adresse qui reçoit les messages

# Adresse(s) qui reçoivent les notifications internes (nouveau signalement,
# nouvelle démarche citoyenne). Séparées par des virgules si plusieurs
# destinataires. Par défaut, réutilise CONTACT_EMAIL.
NOTIF_AGENTS_EMAIL = env_list('NOTIF_AGENTS_EMAIL', os.environ.get('CONTACT_EMAIL', 'contact@keurmassarnord.sn'))


# === SMS (notifications aux citoyens : signalement résolu, démarche mise à jour) ===
# 'console' (par défaut) : le SMS s'affiche dans la console au lieu d'être
# réellement envoyé. 'orange' : voir foncier/sms.py — nécessite un compte
# Orange Developer (non testé faute d'identifiants disponibles ici).
SMS_BACKEND = os.environ.get('SMS_BACKEND', 'console')
SMS_ORANGE_CLIENT_ID = os.environ.get('SMS_ORANGE_CLIENT_ID', '')
SMS_ORANGE_CLIENT_SECRET = os.environ.get('SMS_ORANGE_CLIENT_SECRET', '')
SMS_ORANGE_SENDER = os.environ.get('SMS_ORANGE_SENDER', '')


# === PAIEMENT EN LIGNE (Orange Money / Wave) ===
# 'manuel' (par défaut) : simule un paiement immédiatement confirmé, sans
# aucun compte marchand — utile pour tester tout le parcours citoyen.
# Voir foncier/paiement_gateway.py pour le détail et les avertissements
# sur les backends 'orange_money'/'wave' (non testés faute de comptes réels).
PAIEMENT_BACKEND = os.environ.get('PAIEMENT_BACKEND', 'manuel')
PAIEMENT_ORANGE_MERCHANT_KEY = os.environ.get('PAIEMENT_ORANGE_MERCHANT_KEY', '')
PAIEMENT_ORANGE_CLIENT_ID = os.environ.get('PAIEMENT_ORANGE_CLIENT_ID', '')
PAIEMENT_ORANGE_CLIENT_SECRET = os.environ.get('PAIEMENT_ORANGE_CLIENT_SECRET', '')
PAIEMENT_WAVE_API_KEY = os.environ.get('PAIEMENT_WAVE_API_KEY', '')


# === SÉCURITÉ — réglages activés uniquement en production (DEBUG=False) ===
# En développement local (DEBUG=True), on les laisse désactivés : ils
# imposeraient HTTPS, ce qui casserait `python manage.py runserver` en http.
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
    # HSTS : indique aux navigateurs de toujours utiliser HTTPS pour ce
    # domaine pendant 1 an. À activer seulement une fois le HTTPS confirmé
    # stable (impossible de "revenir" facilement en arrière pour les
    # visiteurs qui ont déjà reçu l'en-tête).
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Si le site est derrière un proxy/load-balancer qui termine le HTTPS
    # (Nginx, Render, Railway...), indispensable pour que Django sache que
    # la requête d'origine était bien en HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# =========================================
# DJANGO-UNFOLD — configuration
# (remplace les anciens UNFOLD_CONFIG / UNFOLD_MAIN_MENU,
#  qui n'étaient pas lus par le package : la seule clé
#  reconnue par django-unfold est "UNFOLD")
# =========================================
UNFOLD = {
    # ---- Identité ----
    "SITE_TITLE": "KMS Nord Admin",
    "SITE_HEADER": "KMS Nord — Foncier & Fiscal",
    "SITE_SUBHEADER": "Administration",
    "SITE_URL": "/",
    # Logo réel déjà présent dans ton projet
    "SITE_LOGO": lambda request: "/static/foncier/images/logo.jpeg",

    "SHOW_HISTORY": True,

    # ---- Couleurs — rampe calculée depuis ton vrai brun DGID #6b4a35 ----
    # (mélange mathématique white/black, aucune valeur inventée)
    "COLORS": {
        "primary": {
            "50":  "248 246 245",
            "100": "240 237 235",
            "200": "222 215 211",
            "300": "199 186 178",
            "400": "169 150 138",
            "500": "137 110 93",
            "600": "107 74 53",    # = #6b4a35, ta couleur de marque exacte
            "700": "91 63 45",
            "800": "73 50 36",
            "900": "56 38 28",
            "950": "41 28 20",
        },
    },

    # ---- Sidebar — reprend ton ancien UNFOLD_MAIN_MENU,
    #      dans la vraie structure attendue par Unfold ----
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Gestion Foncière",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Zones",
                        "icon": "layers",
                        "link": reverse_lazy("admin:foncier_zone_changelist"),
                    },
                    {
                        "title": "Parcelles",
                        "icon": "map",
                        "link": reverse_lazy("admin:foncier_parcelle_changelist"),
                    },
                    {
                        "title": "Propriétaires",
                        "icon": "group",
                        "link": reverse_lazy("admin:foncier_propriétaire_changelist"),
                    },
                ],
            },
            {
                "title": "Finances & Fiscalité",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Taxations",
                        "icon": "description",
                        "link": reverse_lazy("admin:foncier_taxation_changelist"),
                    },
                    {
                        "title": "Paiements",
                        "icon": "credit_card",
                        "link": reverse_lazy("admin:foncier_paiement_changelist"),
                    },
                ],
            },
        ],
    },
}