# Generated by Django 5.2.15 on 2026-07-02 20:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriétaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ni_cni', models.CharField(max_length=20, unique=True, verbose_name='Numéro CNI')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicad', models.CharField(max_length=50, unique=True, verbose_name='Numéro NICAD / Lot')),
                ('superficie', models.FloatField(help_text='Superficie en mètres carrés')),
                ('type_document', models.CharField(choices=[('TF', 'Titre Foncier'), ('BAIL', 'Bail'), ('DELIB', 'Délibération Municipale'), ('ATTES', 'Attestation de cession')], default='DELIB', max_length=10)),
                ('adresse_parcelle', models.CharField(help_text='Quartier ou secteur à Keur Massar Nord', max_length=255)),
                ('valeur_locative', models.DecimalField(decimal_places=2, default=0.0, help_text='Valeur estimée en FCFA', max_digits=12)),
                ('montant_taxe_annuelle', models.DecimalField(decimal_places=2, default=0.0, help_text='CFPB annuelle en FCFA', max_digits=10)),
                ('statut_fiscal', models.CharField(choices=[('A_JOUR', 'À Jour'), ('EN_RETARD', 'En Retard de Paiement'), ('EXONERE', 'Exonéré')], default='A_JOUR', max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles', to='foncier.propriétaire')),
            ],
        ),
    ]
