# Generated by Django 4.2.23 on 2026-07-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiscal', models.CharField(max_length=30, unique=True, verbose_name='Numéro fiscal communal')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('quartier', models.CharField(blank=True, help_text="Quartier de résidence ou d'activité", max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuables', to='foncier.propriétaire')),
            ],
            options={
                'verbose_name': 'Contribuable',
                'verbose_name_plural': 'Contribuables',
            },
        ),
        migrations.CreateModel(
            name='TypeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FONCIERE', 'Taxe foncière communale'), ('PATENTE', 'Patente locale'), ('OCCUPATION', "Taxe d'occupation"), ('MARCHE', 'Taxe sur les marchés'), ('ASSAINISSEMENT', "Redevance d'assainissement"), ('PUBLICITE', 'Taxe sur la publicité')], max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de taxe',
                'verbose_name_plural': 'Types de taxe',
            },
        ),
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_fiscale', models.PositiveIntegerField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxations', to='foncier.contribuable')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxations', to='foncier.parcelle')),
                ('type_taxe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxations', to='foncier.typetaxe')),
            ],
            options={
                'verbose_name': 'Taxation',
                'verbose_name_plural': 'Taxations',
                'ordering': ['-annee_fiscale'],
                'unique_together': {('contribuable', 'type_taxe', 'annee_fiscale', 'parcelle')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces (guichet)'), ('MOBILE', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=15)),
                ('numero_recu', models.CharField(blank=True, max_length=30, unique=True)),
                ('taxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='foncier.taxation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
