# Generated by Django 4.2.23 on 2026-07-03 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0002_contribuable_typetaxe_taxation_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shp', models.BigIntegerField(unique=True, verbose_name='ID du shapefile')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la zone/quartier')),
                ('layer', models.CharField(max_length=100, verbose_name='Couche du shapefile')),
                ('path', models.CharField(max_length=255, verbose_name='Chemin du fichier source')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Géométrie de la zone')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles', to='foncier.zone', verbose_name='Zone/Quartier'),
        ),
    ]
