# Generated by Django 4.2.23 on 2026-07-03 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0003_zone_parcelle_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie de la zone'),
        ),
    ]
