# Generated by Django 5.2.3 on 2026-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0005_profilcitoyen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
