# Generated by Django 4.2.23 on 2026-07-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0006_messagecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='nicad',
            field=models.CharField(max_length=50, verbose_name='Numéro NICAD / Lot'),
        ),
    ]
