# Generated by Django 4.2.23 on 2026-07-22 22:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0007_alter_parcelle_nicad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
