# Generated by Django 4.2.23 on 2026-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0008_alter_parcelle_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifiant court, ex: 'is', 'ir', 'cfpb'", unique=True)),
                ('sigle', models.CharField(blank=True, help_text='Ex: IS, IR, CFPB, NICAD', max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('IMPOTS_DIRECTS', 'Impôts directs'), ('CONTRIBUTIONS_LOCALES', 'Contributions locales'), ('FONCIER_CADASTRE', 'Foncier & Cadastre'), ('DEMARCHES', 'Démarches administratives')], max_length=25)),
                ('resume', models.CharField(help_text='Phrase courte affichée dans la liste', max_length=300)),
                ('qui_est_concerne', models.TextField(blank=True)),
                ('taux_et_calcul', models.TextField(blank=True)),
                ('modalites_declaration', models.TextField(blank=True)),
                ('sanctions', models.TextField(blank=True)),
                ('references_legales', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guide fiscal',
                'verbose_name_plural': 'Guides fiscaux',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
