# Generated by Django 4.2.23 on 2026-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0009_guidefiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RESOLU', 'Résolu')], default='EN_COURS', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
