# Generated by Django 4.2.23 on 2026-07-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0010_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='occupation_sol',
            field=models.CharField(blank=True, max_length=150, verbose_name='Occupation du sol'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='reference_arrete',
            field=models.CharField(blank=True, max_length=100, verbose_name="Référence de l'arrêté"),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='adresse_parcelle',
            field=models.CharField(blank=True, help_text='Quartier ou secteur à Keur Massar Nord', max_length=255),
        ),
    ]
