# Generated by Django 4.2.23 on 2026-08-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0011_parcelle_occupation_sol_parcelle_reference_arrete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifiant court, ex: 'education', 'sante', 'voirie'", unique=True)),
                ('label', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.CharField(blank=True, help_text="Sous-titre affiché sous le nom, ex: 'Écoles, CEM, lycées...'", max_length=255)),
                ('texte_intro', models.TextField(blank=True, help_text="Paragraphe d'introduction affiché en haut du panneau détaillé")),
                ('icone', models.CharField(default='fa-map-pin', help_text="Classe FontAwesome sans le préfixe 'fa-solid', ex: 'fa-school'", max_length=50)),
                ('couleur', models.CharField(default='#2f7a4f', help_text="Couleur hexadécimale utilisée pour l'icône et les accents", max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Catégorie d'infrastructure",
                'verbose_name_plural': "Catégories d'infrastructure",
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quartier', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('EN_TRAVAUX', 'En travaux / réhabilitation'), ('HORS_SERVICE', 'Hors service'), ('PROJETE', 'Projeté')], default='FONCTIONNEL', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='foncier.categorieinfrastructure')),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'ordering': ['categorie__ordre', 'nom'],
            },
        ),
    ]
