# Generated by Django 4.2.23 on 2026-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0012_categorieinfrastructure_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('chapo', models.TextField(help_text="Court résumé affiché sur la carte de l'accueil (quelques phrases).", max_length=400)),
                ('contenu', models.TextField(blank=True, help_text="Texte complet de l'article, si vous voulez une page de détail.")),
                ('categorie', models.CharField(choices=[('AVIS', 'Avis'), ('PROJET', 'Projet'), ('COMMUNIQUE', 'Communiqué'), ('APPEL_OFFRES', "Appel d'offres"), ('EVENEMENT', 'Événement')], default='AVIS', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date_publication', models.DateField(verbose_name='Date à afficher')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True, help_text="Décochez pour garder l'article en brouillon (invisible sur le site).", verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
    ]
