# Generated by Django 5.2.3 on 2026-09-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0025_infrastructure_id_shp'),
        ('foncier', '0027_parcelle_identifiants'),
    ]

    operations = [
    ]
