# Generated by Django 5.2.3 on 2026-09-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0029_parcelle_simulation_fiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxation',
            name='simulation_fiscale',
            field=models.BooleanField(default=False, help_text="Coché si cette taxation provient d'une simulation académique, et non d'une émission réelle par les services de la commune.", verbose_name='Taxation simulée'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='simulation_fiscale',
            field=models.BooleanField(default=False, help_text="Coché si le montant de taxe/valeur locative provient d'une simulation académique, et non d'une déclaration ou d'un calcul réel.", verbose_name='Montant fiscal simulé'),
        ),
    ]
