# Generated by Django 5.2.3 on 2026-09-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0031_profilagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilagent',
            name='fonction',
            field=models.CharField(blank=True, help_text='Ex : Maire, Chef du Service Cadastre, Chef du Service Fiscalite', max_length=150, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='profilagent',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone'),
        ),
    ]
