# Generated by Django 5.2.3 on 2026-09-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0032_alter_profilagent_fonction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_fiscale', models.PositiveIntegerField()),
                ('occupation_declaree', models.CharField(choices=[('Terrain Nu', 'Terrain Nu'), ('Bâti', 'Bâti'), ('Zone de culture', 'Zone de culture')], max_length=30)),
                ('superficie_declaree', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour reprendre la superficie cadastrale.', max_digits=10, null=True)),
                ('commentaire_citoyen', models.TextField(blank=True, verbose_name='Précisions apportées')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='declarations_fiscales/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='foncier.contribuable')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='foncier.parcelle')),
                ('taxation_generee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_origine', to='foncier.taxation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_traitees', to=settings.AUTH_USER_MODEL)),
                ('type_taxe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='foncier.typetaxe')),
            ],
            options={
                'verbose_name': 'Déclaration fiscale',
                'verbose_name_plural': 'Déclarations fiscales',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
