# Generated by Django 5.2.3 on 2026-09-18 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0033_declarationfiscale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoursFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveSmallIntegerField(choices=[(1, 'Recours (contestation initiale)'), (2, "Redressement (vérification de l'historique des paiements)")], default=1)),
                ('motif', models.TextField(verbose_name='Motif de la contestation')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='recours_fiscaux/')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('EN_EXAMEN', "En cours d'examen"), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='SOUMIS', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('decision_commentaire', models.TextField(blank=True, verbose_name='Explication de la décision')),
                ('ancien_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nouveau_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours_fiscaux', to='foncier.contribuable')),
                ('recours_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redressement', to='foncier.recoursfiscal')),
                ('taxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='foncier.taxation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recours fiscal',
                'verbose_name_plural': 'Recours fiscaux',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
