# Generated by Django 5.2.3 on 2026-09-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0034_recoursfiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeImmatriculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ni_cni', models.CharField(max_length=20, verbose_name='Numéro CNI')),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation_declaree', models.CharField(choices=[('Terrain Nu', 'Terrain Nu'), ('Bâti', 'Bâti'), ('Zone de culture', 'Zone de culture')], max_length=30)),
                ('piece_jointe', models.FileField(help_text='Acte de vente, titre foncier ou attestation de cession (obligatoire).', upload_to='immatriculations/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('contribuable_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='foncier.contribuable')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_immatriculation', to='foncier.parcelle')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immatriculations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de première immatriculation',
                'verbose_name_plural': 'Demandes de première immatriculation',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
