# Generated by Django 5.2.3 on 2026-09-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0035_demandeimmatriculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeExoneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('RELIGIEUX', 'Bâtiment religieux (mosquée, église...)'), ('PUBLIC', 'Établissement public (école, hôpital, administration...)'), ('DIPLOMATIQUE', 'Mission diplomatique'), ('AUTRE', 'Autre motif')], max_length=20)),
                ('description', models.TextField(blank=True, help_text="Détaillez votre situation si besoin (surtout pour 'Autre motif').", verbose_name='Précisions')),
                ('piece_jointe', models.FileField(help_text='Justificatif (attestation religieuse, arrêté, décision administrative...).', upload_to='exonerations/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_exoneration', to='foncier.contribuable')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_exoneration', to='foncier.parcelle')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exonerations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'exonération",
                'verbose_name_plural': "Demandes d'exonération",
                'ordering': ['-date_soumission'],
            },
        ),
    ]
