# Generated by Django 5.2.3 on 2026-09-19 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0036_demandeexoneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_echeances', models.PositiveSmallIntegerField(help_text='Entre 2 et 4 échéances.', verbose_name="Nombre d'échéances souhaité")),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('TERMINE', 'Terminé (toutes échéances payées)')], default='SOUMIS', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_paiement', to='foncier.contribuable')),
                ('taxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_paiement', to='foncier.taxation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_paiement_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='EcheancePlanPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name="N° de l'échéance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=15)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeance_origine', to='foncier.paiement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='foncier.planpaiement')),
            ],
            options={
                'verbose_name': 'Échéance de plan de paiement',
                'verbose_name_plural': 'Échéances de plan de paiement',
                'ordering': ['plan', 'numero'],
            },
        ),
    ]
