# Generated by Django 5.2.3 on 2026-09-20 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0037_planpaiement_echeanceplanpaiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveau_nom', models.CharField(max_length=100, verbose_name='Nom du nouveau propriétaire')),
                ('nouveau_prenom', models.CharField(max_length=100, verbose_name='Prénom du nouveau propriétaire')),
                ('nouveau_cni', models.CharField(max_length=20, verbose_name='Numéro CNI du nouveau propriétaire')),
                ('nouveau_telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('nouveau_email', models.EmailField(blank=True, max_length=254, verbose_name='Email (facultatif)')),
                ('piece_jointe', models.FileField(help_text='Acte de vente ou tout document attestant du transfert de propriété (obligatoire).', upload_to='mutations/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('nouveau_contribuable_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutation_origine', to='foncier.contribuable')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mutation', to='foncier.parcelle')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de mutation fiscale',
                'verbose_name_plural': 'Demandes de mutation fiscale',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
