# Generated by Django 5.2.3 on 2026-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0038_demandemutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='parcelle',
            field=models.ForeignKey(blank=True, help_text='Parcelle qui contient cette infrastructure (déterminée automatiquement par croisement spatial).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to='foncier.parcelle'),
        ),
    ]
