# Generated by Django 5.2.3 on 2026-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0039_infrastructure_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeservice',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='statut_paiement',
            field=models.CharField(choices=[('NON_REQUIS', 'Non requis (démarche gratuite)'), ('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé')], default='NON_REQUIS', max_length=15),
        ),
        migrations.AddField(
            model_name='typedemande',
            name='tarif',
            field=models.DecimalField(decimal_places=0, default=0, help_text='0 = démarche gratuite. Si > 0, le paiement est exigé avant délivrance du document.', max_digits=10, verbose_name='Tarif (FCFA)'),
        ),
    ]
