# Generated by Django 5.2.3 on 2026-09-21 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0040_demandeservice_montant_paye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='parcelle_active',
            field=models.BooleanField(default=True, help_text='Décoché automatiquement si cette parcelle a été fusionnée ou morcelée (remplacée par une ou plusieurs nouvelles parcelles).', verbose_name='Parcelle active'),
        ),
        migrations.CreateModel(
            name='DemandeMorcellementFusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('MORCELLEMENT', 'Morcellement (diviser une parcelle)'), ('FUSION', 'Fusion (regrouper plusieurs parcelles)')], max_length=15)),
                ('justification', models.TextField(verbose_name='Motif de la demande')),
                ('piece_jointe', models.FileField(help_text='Plan du géomètre-expert ou tout document justificatif (obligatoire).', upload_to='morcellement_fusion/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_EXAMEN', "En cours d'examen"), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=15)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_morcellement_fusion', to=settings.AUTH_USER_MODEL)),
                ('parcelles_concernees', models.ManyToManyField(related_name='demandes_morcellement_fusion_origine', to='foncier.parcelle')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morcellements_fusions_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de morcellement/fusion',
                'verbose_name_plural': 'Demandes de morcellement/fusion',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='demande_origine',
            field=models.ForeignKey(blank=True, help_text="Demande de morcellement/fusion à l'origine de cette parcelle, le cas échéant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles_resultantes', to='foncier.demandemorcellementfusion'),
        ),
    ]
