# Generated by Django 5.2.3 on 2026-09-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0041_parcelle_parcelle_active_demandemorcellementfusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Attributs specifiques au type d'infrastructure (horaires, telephone, nombre d'employes, services, etc.), sous forme libelle -> valeur."),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='sous_type',
            field=models.CharField(blank=True, help_text='Sous-categorie precise (ex: Pharmacie, Poste de sante, Centre de sante...).', max_length=150),
        ),
    ]
