# Generated by Django 5.2.3 on 2026-09-23 20:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0042_infrastructure_details_infrastructure_sous_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartierOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du quartier')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie du quartier')),
            ],
            options={
                'verbose_name': 'Quartier officiel',
                'verbose_name_plural': 'Quartiers officiels',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SectionCadastrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro de section')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie de la section')),
            ],
            options={
                'verbose_name': 'Section cadastrale',
                'verbose_name_plural': 'Sections cadastrales',
                'ordering': ['numero'],
            },
        ),
    ]
