# Generated by Django 5.2.3 on 2026-09-23 20:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0043_quartierofficiel_sectioncadastrale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'entite")),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie de la limite')),
            ],
            options={
                'verbose_name': 'Limite administrative',
                'verbose_name_plural': 'Limites administratives',
                'ordering': ['nom'],
            },
        ),
    ]
