# Generated by Django 5.2.3 on 2026-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0044_limiteadministrative'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre / légende')),
                ('photo', models.ImageField(upload_to='galerie/', verbose_name='Photo')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Détermine l'ordre d'affichage (les plus petits nombres en premier).")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de la galerie',
                'verbose_name_plural': 'Photos de la galerie',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
