# Generated by Django 5.2.3 on 2026-10-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0045_photogalerie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteThematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la carte')),
                ('explication', models.TextField(help_text='Quelques phrases expliquant ce que montre cette carte et pourquoi elle est utile.', verbose_name='Explication / signification')),
                ('image', models.ImageField(upload_to='cartotheque/', verbose_name='Image de la carte')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Détermine l'ordre d'affichage (les plus petits nombres en premier).")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carte thématique',
                'verbose_name_plural': 'Cartothèque (cartes thématiques)',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
